[toolchain]
anchor_version = "0.29.0"    # `anchor-cli` version to use(requires `avm`)
solana_version = "1.18.14"    # Solana version to use(applies to all Solana tools)

[features]
seeds = false
skip-lint = false

[programs.localnet]
demo_program = "EqMougERTbqQ5VhjXL6hxcZeZVQamFRK68AhfHtC1Nsy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/thewuh/.config/solana/deployer.json"

[scripts]
test = "ts-mocha -p ./protocol/tsconfig.json -t 1000000 protocol/ts/tests/**/*.test.ts"
demo_program = "ts-mocha -p ./protocol/tsconfig.json -t 1000000 protocol/ts/tests/demo-program.test.ts"

[workspace]
members= [
  "protocol/programs/demo-program",
]
types="protocol/ts/src/idl"
